CREATE OR REPLACE TABLE `netflix-pipeline-gcp.netflix_analytical.fact_belief_data` AS
SELECT
    SAFE_CAST(NULLIF(USERID, '') AS INT64) AS USER_ID,
    SAFE_CAST(NULLIF(MOVIEID, '') AS INT64) AS MOVIE_ID,
    SAFE_CAST(ISSEEN AS INT64) AS IS_SEEN,
    SAFE.PARSE_DATE('%Y-%m-%d', WATCHDATE) AS WATCH_DATE,
    SAFE_CAST(USERELICITRATING AS FLOAT64) AS USER_ELICIT_RATING,
    SAFE_CAST(USERPREDICTRATING AS FLOAT64) AS USER_PREDICT_RATING,
    SAFE_CAST(USERCERTAINTY AS FLOAT64) AS USER_CERTAINTY,
    COALESCE(
        SAFE.PARSE_TIMESTAMP('%Y-%m-%d %H:%M:%S%Ez', TSTAMP),
        SAFE.PARSE_TIMESTAMP('%Y-%m-%d %H:%M:%S', TSTAMP)
    ) AS BELIEF_TS,
    SAFE_CAST(MONTH_IDX AS INT64) AS MONTH_IDX,
    SAFE_CAST(SOURCE AS INT64) AS SOURCE,
    SAFE_CAST(SYSTEMPREDICTRATING AS FLOAT64) AS SYSTEM_PREDICT_RATING
FROM `netflix-pipeline-gcp.netflix_raw.raw_belief_data`
WHERE
    USERID IS NOT NULL
    AND MOVIEID IS NOT NULL;
